name: Fetch GitHub Issues

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run issue fetcher script
        run: python api_client/api_client.py
      - name: Upload issue JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-issues
          path: github_issues.json
