name: Build and Test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Dev'
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          cd my-static-website
          npm install
          npm run build
          npm run test
          ls -ltr
          ls -ltr tests
          echo "Test results generated."

      - name: Zip artifact for deployment
        run: zip -r release.zip my-static-website/*

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: my-static-website/tests/
        

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip