name: Infra Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        default: 'Dev'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-init-plan:
    runs-on: ubuntu-latest
    environment: Dev  # Use the Dev environment for both jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

  approval:
    needs: terraform-init-plan
    runs-on: ubuntu-latest
    environment: Approval  # Use the Approval environment for approval
    steps:
      - name: Approval Step
        run: echo "Deployment approved, proceeding to apply."
  terraform-apply:
    needs: approval
    runs-on: ubuntu-latest
    environment: Dev  # Use the Dev environment for apply

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -var-file="terraform.tfvars" -auto-approve