name: WebApp Deployment Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'static-website/**'  # Trigger only when files in static-website directory change
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml

  sonarqube-scan:
    needs: build
    uses: ./.github/workflows/sonarqube-scan.yml

  deploy-dev:
    needs: sonarqube-scan
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Dev'
      app-name: '1-webapp-dev-fmc'

  approve-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: 'staging'
    steps:
      - name: Staging Approval Step
        run: echo "Staging deployment approved, proceeding to apply."

  deploy-staging:
    needs: approve-staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Staging'
      app-name: '1-webapp-staging-fmc'

  approve-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: '
