name: WebApp Deployment Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'static-website/**'  # Trigger only when files in static-website directory change
  workflow_dispatch:

jobs:
  build:
    uses: .github/workflows/workflow_templates/build-and-test.yml@main  # Corrected to use a relative path

  sonarqube-scan:
    needs: build
    uses: ./workflow_templates/sonarqube-scan.yml@main  # Corrected to use a relative path

  deploy-dev:
    needs: sonarqube-scan
    uses: ./workflow_templates/deploy.yml  # Corrected to use a relative path
    with:
      environment: 'Dev'
      app-name: '1-webapp-dev-fmc'

  approve-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: 'Approval'
    steps:
      - name: Staging Approval Step
        run: echo "Staging deployment approved, proceeding to apply."

  deploy-staging:
    needs: approve-staging
    uses: ./workflow_templates/deploy.yml  # Corrected to use a relative path
    with:
      environment: 'Dev'
      app-name: '1-webapp-dev-fmc'

  approve-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: 'Approval'
    steps:
      - name: Prod Approval Step
        run: echo "Production deployment approved, proceeding to apply."

  deploy-prod:
    needs: approve-prod
    uses: ./workflow_templates/deploy.yml  # Corrected to use a relative path
    with:
      environment: 'Dev'
      app-name: '1-webapp-dev-fmc'