name: Build and deploy Node.js app to Azure Web App - webapp-dev-fmc

on:
  push:
    branches:
      - main
    paths:
      - 'static-website/**'  # Trigger only when files in static-website directory change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: npm install, build, and test
        run: |
          cd my-static-website
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip my-static-website/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read # This is required for actions/checkout
      id-token: write # This is required for Azure login

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d my-static-website
      - name: Move contents to wwwroot
        run: |
          mkdir -p wwwroot
          mv my-static-website/ wwwroot/
          ls -ltr
          ls -ltr wwwroot
          rm -rf my-static-website
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: '1-webapp-prod-fmc' # Update to your Dev environment app name
          package: wwwroot