name: WebApp Deployment Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'static-website/**'  # Trigger only when files in static-website directory change
  workflow_dispatch:
permissions:
   id-token: write
   contents: read

jobs:

  build:
    uses: ./.github/workflows/build_and_test.yml

    
  sonarqube-scan:
    needs: build
    uses: ./.github/workflows/sonar_scan.yml
    secrets: inherit
    
  deploy-dev:
    needs: sonarqube-scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: 'Dev'
      app-name: '1-webapp-dev-fmc'

  approve-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: 'Approval'
    steps:
      - name: Staging Approval Step
        run: echo "Staging deployment approved, proceeding to apply."

  deploy-staging:
    needs: approve-staging
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: 'Dev'
      app-name: '1-webapp-dev-fmc'

  approve-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: 'Approval '
    steps:
      - name: Prod Approval Step
        run: echo "Production deployment approved, proceeding to apply."

  deploy-prod:
    needs: approve-prod
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Dev'
      app-name: '1-webapp-prod-fmc'
